version: '3.9'
services:
  rtml:
    build: ./rtmp
    ports:
      - '1935:1935'
      - '8080:8080'
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
  auth:
    build: ./auth
    container_name: auth_server

#   nodejs:
#     build: ./auth/dockerfile
#     ports:
#       - '8000:8000'
#     depends_on:
#       - mysql
#     networks:
#       - my_network

#   mysql:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: 
#       MYSQL_DATABASE: church
#     networks:
#       - my_network

# networks:
#   my_network:
#     driver: bridge
